spring:
  datasource:
    password: ${SPRING_DATASOURCE_USERNAME:root}
    username: ${SPRING_DATASOURCE_PASSWORD:root}
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL}:5432/${POSTGRES_DB}?user=${SPRING_DATASOURCE_USERNAME}&password=${SPRING_DATASOURCE_PASSWORD}&sslmode=require
  flyway:
    sql-migration-separator: __
    user: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL}:5432/${POSTGRES_DB}?user=${SPRING_DATASOURCE_USERNAME}&password=${SPRING_DATASOURCE_PASSWORD}&sslmode=require
    sql-migration-suffixes: .sql
  jpa:
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  servlet:
    session:
      cookie:
        secure: 'true'
  port: ${PORT}

external:
  url: https://api.geointellect.com
  api-key-name: test_api_kz_1
  api-key-value: 53500775-c1ac-4a8f-9790-2170fdb9c3b4
